### ISSUE TITLE
Minifying Issues

### ISSUE THREAD

**Issue by CopBill** [PenetratingShot/Borealis#12]
### Hello, Cop Bill here.

In your `distrib` folder, you have some issues:

-  The `borealis.css` file is minified and has completely different style rules than the `borealis.min.css` file which isn't even minified. 
- Both files are different

Ways to fix this:

1) Copy and paste the style rules from whichever file is correct and put it in both files
2) Go to a CSS minifier and change the minified file so it actually has minified CSS

**Comment by talonbragg** [comment]
We are on it

**Comment by PenetratingShot** [comment]
Hey thanks bro
