### ISSUE TITLE
Framework not Used

### ISSUE THREAD

**Issue by CopJoe** [PenetratingShot/Borealis#13]
### Hello, Cop Joe here.

In your main website, you have some issues:

- You don't use your own framework (by linking to `borealis.min.css`)
- Your template is just a copy of the Github repo, which again, also doesn't use Borealis
- The way you are linking in the documentation is not correct, the MIME type is plain text, not CSS
- No documentation

Ways to fix this:

1) Learn how to use your own framework, and make docs
2) Figure out a secure way to link to framework
3) Link to framework
4) Use Framework

**Comment by talonbragg** [comment]
About the documentation, we are not even finished with this yet, so, why don't you leave while we just work on our problems. I bet you have problems of you own, GO WORK ON THOSE! 

**Comment by KingPixil** [comment]
Ok, work on the documentation, what about everything else?

Do you know how to use your own framework? If so, why don't you use it?

**Comment by CopJoe** [comment]
Why don't you use the framework?

**Comment by PenetratingShot** [comment]
Guys, guys. Let's not fight over this

**Comment by CopBill** [comment]
@talonbragg @PenetratingShot The documentation doesn't have anything to do with linking files. Even without the documentation you still need to link to your own framework.
