### ISSUE TITLE
Team code

### ISSUE THREAD

**Issue by talonbragg** [PenetratingShot/Borealis#14]
I want you guys to go on to [cloud 9](https://c9.io) and make and account. Just tell me the account name on this issue. That way I can share the repo with you on there and we can se what each other is doing. It is like google docs where you can see what everybody is doing at the same time as you.

**Comment by talonbragg** [comment]
The repo is for borealis

**Comment by PenetratingShot** [comment]
It requires a credit card. I know there's no charge, but my dad won't let me

**Comment by talonbragg** [comment]
No it doesn't, It didn't for me
